//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.28 at 06:12:50 PM GST 
//


package mis.lis.report;

import lombok.Getter;
import lombok.Setter;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conclusion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="diagnosis" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="detail" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="physician" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="verified" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "conclusion",
    "diagnosis",
    "detail"
})
@XmlRootElement(name = "info")
public class Info {

    @XmlElement(required = true)
    protected Object conclusion;
    @XmlElement(required = true)
    protected Object diagnosis;
    @XmlElement(required = true)
    protected Object detail;
    @XmlAttribute(name = "physician")
    @XmlSchemaType(name = "anySimpleType")
    protected String physician;
    @XmlAttribute(name = "verified")
    @XmlSchemaType(name = "anySimpleType")
    protected String verified;
    @XmlAttribute(name = "date")
    @XmlSchemaType(name = "anySimpleType")
    protected String date;
    @XmlAttribute(name = "login")
    @Getter
    @Setter
    private String login;

    /**
     * Gets the value of the conclusion property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getConclusion() {
        return conclusion;
    }

    /**
     * Sets the value of the conclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setConclusion(Object value) {
        this.conclusion = value;
    }

    /**
     * Gets the value of the diagnosis property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDiagnosis() {
        return diagnosis;
    }

    /**
     * Sets the value of the diagnosis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDiagnosis(Object value) {
        this.diagnosis = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDetail() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDetail(Object value) {
        this.detail = value;
    }

    /**
     * Gets the value of the physician property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysician() {
        return physician;
    }

    /**
     * Sets the value of the physician property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysician(String value) {
        this.physician = value;
    }

    /**
     * Gets the value of the verified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerified() {
        return verified;
    }

    /**
     * Sets the value of the verified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerified(String value) {
        this.verified = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

}

