//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.28 at 06:12:50 PM GST 
//


package mis.lis.report;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mis.lis.api.report package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mis.lis.api.report
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Attachments }
     * 
     */
    public Attachments createAttachments() {
        return new Attachments();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link Report.Additional }
     * 
     */
    public Report.Additional createReportAdditional() {
        return new Report.Additional();
    }

    /**
     * Create an instance of {@link Report.Additional.Statdata }
     * 
     */
    public Report.Additional.Statdata createReportAdditionalStatdata() {
        return new Report.Additional.Statdata();
    }

    /**
     * Create an instance of {@link Report.Additional.Statdata.Record }
     * 
     */
    public Report.Additional.Statdata.Record createReportAdditionalStatdataRecord() {
        return new Report.Additional.Statdata.Record();
    }

    /**
     * Create an instance of {@link Report.Additional.Statdata.Record.Item }
     * 
     */
    public Report.Additional.Statdata.Record.Item createReportAdditionalStatdataRecordItem() {
        return new Report.Additional.Statdata.Record.Item();
    }

    /**
     * Create an instance of {@link Report.Additional.Statdata.Record.Item.Attributes }
     * 
     */
    public Report.Additional.Statdata.Record.Item.Attributes createReportAdditionalStatdataRecordItemAttributes() {
        return new Report.Additional.Statdata.Record.Item.Attributes();
    }

    /**
     * Create an instance of {@link Result.Service }
     * 
     */
    public Result.Service createResultService() {
        return new Result.Service();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link Info }
     * 
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link Attachments.Attachment }
     * 
     */
    public Attachments.Attachment createAttachmentsAttachment() {
        return new Attachments.Attachment();
    }

    /**
     * Create an instance of {@link Report.PrintedReport }
     * 
     */
    public Report.PrintedReport createReportPrintedReport() {
        return new Report.PrintedReport();
    }

    /**
     * Create an instance of {@link Report.Additional.Lis }
     * 
     */
    public Report.Additional.Lis createReportAdditionalLis() {
        return new Report.Additional.Lis();
    }

    /**
     * Create an instance of {@link Report.Additional.Ris }
     * 
     */
    public Report.Additional.Ris createReportAdditionalRis() {
        return new Report.Additional.Ris();
    }

    /**
     * Create an instance of {@link Report.Additional.Statdata.Record.Item.Attributes.Attribute }
     * 
     */
    public Report.Additional.Statdata.Record.Item.Attributes.Attribute createReportAdditionalStatdataRecordItemAttributesAttribute() {
        return new Report.Additional.Statdata.Record.Item.Attributes.Attribute();
    }

    /**
     * Create an instance of {@link Result.Service.Indicator }
     * 
     */
    public Result.Service.Indicator createResultServiceIndicator() {
        return new Result.Service.Indicator();
    }

}
