//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.28 at 06:12:50 PM GST 
//


package mis.lis.report;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for svcType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="svcType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="COMPLETE"/>
 *     &lt;enumeration value="PARTIAL"/>
 *     &lt;enumeration value="DECLINE"/>
 *     &lt;enumeration value="EMPTY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "svcType")
@XmlEnum
public enum SvcType {

    COMPLETE,
    PARTIAL,
    DECLINE,
    EMPTY;

    public String value() {
        return name();
    }

    public static SvcType fromValue(String v) {
        return valueOf(v);
    }

}

